added emotion analyzer module and attched in the open ai api
neocadia/FastChat pull request #2
Opened 2023-09-02 22:13 UTC by soulsyrup

2023-09-03 04:12 UTC, digisomni requested changes

2023-09-03 04:12 UTC, digisomni commented on fastchat/modules/emotion_analyzer.py
> +@app.post("/emotion_analyze")
Should this be here?

2023-09-03 04:12 UTC, digisomni commented on fastchat/serve/openai_api_server.py
> +@app.post("/emotion_analyze")
Does the emotion analyze module need to be imported? Also this should start with /api/v1/

2023-09-03 04:12 UTC, digisomni commented on fastchat/serve/openai_api_server.py
> +def analyze_text(item: Text):
How is this linking back to the module?

2023-09-04 12:45 UTC, soulsyrup commented on fastchat/modules/emotion_analyzer.py
> +@app.post("/emotion_analyze")
no, I removed it now

2023-09-04 12:46 UTC, soulsyrup commented on fastchat/serve/openai_api_server.py
> +def analyze_text(item: Text):
I changed this part, is it working now?

2023-09-04 12:47 UTC, soulsyrup commented on fastchat/serve/openai_api_server.py
> +@app.post("/emotion_analyze")
I've added the import and also the api/v1/

2023-09-04 15:35 UTC, merged